apiVersion: v1
kind: Service
metadata:
  name: mytask-service
spec:
  selector:
    app: mytask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Expose the service via a LoadBalancer

