# talosconfig.yaml
cluster:
  name: my-cluster
  controlPlaneEndpoint: "https://10.5.0.2:6443"
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        type: "ethernet"
    routes:
      - to: 0.0.0.0/0
        via: 10.1.1.4
nodes:
  - name: control-plane
    role: control-plane
    ip: 10.5.0.2
    os: linux
    cpu: 2
    memory: 4096
    network: eth0
    containerRuntime: containerd
    k8sVersion: v1.22.0
    storage:
      root:
        size: 20Gi

